[CmdletBinding(SupportsShouldProcess, ConfirmImpact = "High")]
param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Get-NormalizedPath {
    param([Parameter(Mandatory)][string]$Path)

    return [IO.Path]::GetFullPath(
        [Environment]::ExpandEnvironmentVariables($Path)
    ).TrimEnd('\')
}

function Test-ExpectedPath {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string[]]$AllowedPaths
    )

    $normalizedPath = Get-NormalizedPath -Path $Path
    return @(
        $AllowedPaths |
            ForEach-Object { Get-NormalizedPath -Path $_ } |
            Where-Object { $_ -ieq $normalizedPath }
    ).Count -gt 0
}

$runningCode = @(
    Get-Process -ErrorAction SilentlyContinue |
        Where-Object { $_.ProcessName -match '^Code($| -)' }
)
if ($runningCode.Count -gt 0) {
    Write-Host "[ERROR] VS Code is running." -ForegroundColor Red
    Write-Host "Close every VS Code window and run this script from an external PowerShell window."
    exit 1
}

$userInstallRoot = Join-Path $env:LOCALAPPDATA "Programs\Microsoft VS Code"
$systemInstallRoots = @(
    Join-Path $env:ProgramFiles "Microsoft VS Code"
)
if (${env:ProgramFiles(x86)}) {
    $systemInstallRoots += Join-Path ${env:ProgramFiles(x86)} "Microsoft VS Code"
}

$allowedInstallRoots = @($userInstallRoot) + @($systemInstallRoots)
$installRoots = @(
    $allowedInstallRoots |
        Where-Object { Test-Path -LiteralPath $_ -PathType Container } |
        Sort-Object -Unique
)
$dataPaths = @(
    Join-Path $env:APPDATA "Code"
    Join-Path $env:USERPROFILE ".vscode"
)

Write-Host "VS Code clean uninstall" -ForegroundColor Cyan
Write-Host ""
Write-Host "Program installations found:"
if ($installRoots.Count -eq 0) {
    Write-Host "  (none)" -ForegroundColor DarkGray
}
else {
    $installRoots | ForEach-Object { Write-Host "  $_" }
}
Write-Host "User data to remove:"
foreach ($path in $dataPaths) {
    $state = if (Test-Path -LiteralPath $path) { "found" } else { "not found" }
    Write-Host "  $path [$state]"
}
Write-Host ""
Write-Host "Project folders, project .vscode settings, Git repositories, Python installations, and .venv folders are not targeted." -ForegroundColor Green

if (-not $Force -and -not $WhatIfPreference) {
    $answer = Read-Host "Type DELETE to uninstall VS Code and remove all listed user data"
    if ($answer -cne "DELETE") {
        Write-Host "Cancelled. Nothing was changed." -ForegroundColor Yellow
        exit 0
    }
}

# The explicit DELETE prompt above is the single confirmation for this script.
# Suppress the additional per-operation confirmation generated by ShouldProcess.
if (-not $WhatIfPreference) {
    $ConfirmPreference = "None"
}

foreach ($installRoot in $installRoots) {
    if (-not (Test-ExpectedPath -Path $installRoot -AllowedPaths $allowedInstallRoots)) {
        throw "Refusing to process an unexpected installation path: $installRoot"
    }

    $uninstaller = Join-Path $installRoot "unins000.exe"
    if (Test-Path -LiteralPath $uninstaller -PathType Leaf) {
        if ($PSCmdlet.ShouldProcess($installRoot, "Run the official VS Code uninstaller")) {
            $process = Start-Process `
                -FilePath $uninstaller `
                -ArgumentList @("/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART") `
                -Wait `
                -PassThru
            if ($process.ExitCode -ne 0) {
                throw "VS Code uninstaller failed with exit code $($process.ExitCode): $uninstaller"
            }
        }
    }
    else {
        Write-Host "[WARN] Uninstaller was not found; the known installation directory will be removed directly: $installRoot" -ForegroundColor Yellow
    }

    if (Test-Path -LiteralPath $installRoot) {
        if ($PSCmdlet.ShouldProcess($installRoot, "Remove the remaining VS Code installation directory")) {
            Remove-Item -LiteralPath $installRoot -Recurse -Force
        }
    }
}

foreach ($path in $dataPaths) {
    if (-not (Test-ExpectedPath -Path $path -AllowedPaths $dataPaths)) {
        throw "Refusing to process an unexpected user-data path: $path"
    }

    if (Test-Path -LiteralPath $path) {
        if ($PSCmdlet.ShouldProcess($path, "Remove VS Code user data and extensions")) {
            Remove-Item -LiteralPath $path -Recurse -Force
        }
    }
}

Write-Host ""
if ($WhatIfPreference) {
    Write-Host "[OK] Preview complete. Nothing was changed." -ForegroundColor Green
}
else {
    Write-Host "[OK] VS Code and its user data were removed." -ForegroundColor Green
    Write-Host "Restart Windows before installing VS Code again."
}
